# Project: Matos by CloudMatos (https://www.cloudmatos.com/) - Automate your Cloud Security & Compliance
# Asset: aws-codebuild
# Licensing: MIT
---
- hosts: "localhost"
  connection: "local"
  gather_facts: true

  pre_tasks:
  - name: Validate Input
    assert:
      that:
      - aws_access_key is defined
      - aws_secret_key is defined
      - aws_region is defined
      - action is defined
      - project_name is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: Get Project buildspec files
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}"
        aws codebuild batch-get-projects
        --name "{{ project_name }}" 
        --query 'projects[0].source.buildspec'
        --region {{ region }}
      register: project_builds_bs
      when: action is defined and action == 'codebuild_buildspec_validate'
    - set_fact:
          project_buildspec : "{{ project_builds_bs.stdout }}" 

    # Validate whether project is having a buildspec.yml
    - name: Verify the last invoked time is greater than 90 days
      debug:
        msg: "{{ project_name }} doesn't have a custom buildspec.yml"
      when: ("buildspec.yml" not in project_buildspec)
      register: is_buildspec
      failed_when: "'An error occurred' in is_buildspec.stderr"
      changed_when: "is_buildspec.changed == 'true'"

   