# Project: Matos by CloudMatos (https://www.cloudmatos.com/) - Automate your Cloud Security & Compliance
# Asset: aws-eks
# Licensing: MIT

---
- hosts: "localhost"
  connection: "local"
  gather_facts: true

  vars:
    region: "{{ aws_region }}"

  pre_tasks:
  - name: Validate Input
    assert:
      that:
      - aws_access_key is defined
      - aws_secret_key is defined
      - aws_region is defined
      - action is defined
      - eks_cluster_name is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    # Grab the last execution datetime of the project
    - name: Update EKS cluster config
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}"
        aws eks update-cluster-config 
        --name "{{ eks_cluster_name  }}" 
        --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true
        --region {{ region }}
      when: action is defined and action == 'eks_disable_public_endpoint'
      register: eks_disable_enable
      failed_when: "'An error occurred' in eks_disable_enable.stderr"
      changed_when: "eks_disable_enable.changed == 'true'"
   