- name:
  command: 'aws configure set aws_access_key_id "{{aws_access_key}}"'
- name:
  command: 'aws configure set aws_secret_access_key "{{aws_secret_key}}"'
- name:
  command: 'aws configure set default.region "{{aws_region}}"'
    